export type AddressType = "SHIPPING" | "BILLING";

export interface Address {
  id: number;

  address_type: AddressType;

  first_name: string;
  last_name: string;

  phone_number: string | null;

  address_line_1: string;
  address_line_2: string | null;

  city: string;
  state: string;
  country: string;
  postal_code: string | null;

  is_default: boolean;

  created_at: string;
  updated_at: string;

  /**
   * Compatibility fields for existing frontend address UI.
   * These are generated by the API normalizer.
   */
  phone?: string | null;
  company?: string;
  is_default_shipping?: boolean;
  is_default_billing?: boolean;
}

/**
 * This type intentionally supports both the new backend contract
 * and the older address form currently used elsewhere in the frontend.
 *
 * createAddress/updateAddress normalize it before sending to Django.
 */
export interface AddressPayload {
  address_type?: AddressType;

  first_name: string;
  last_name: string;

  phone_number?: string;
  phone?: string;

  address_line_1: string;
  address_line_2?: string;

  city: string;
  state: string;
  country: string;
  postal_code?: string;

  is_default?: boolean;

  /**
   * Legacy frontend fields.
   */
  company?: string;
  is_default_shipping?: boolean;
  is_default_billing?: boolean;
}