# Generated by Django 6.1.1 on 2026-09-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productmedia_unique_primary_image_per_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmedia',
            name='unique_primary_image_per_product',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_default_variant_per_product',
        ),
    ]
